/*
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RuleDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/gyaltso/mdsca/ruledsl/parser/antlr/internal/InternalRuleDsl.tokens");
	}
}
