/*
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.gyaltso.mdsca.ruledsl.parser.antlr.internal.InternalRuleDslParser;
import org.gyaltso.mdsca.ruledsl.services.RuleDslGrammarAccess;

public class RuleDslParser extends AbstractAntlrParser {

	@Inject
	private RuleDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRuleDslParser createParser(XtextTokenStream stream) {
		return new InternalRuleDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RulesFile";
	}

	public RuleDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RuleDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
