/*
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RuleDslStandaloneSetup extends RuleDslStandaloneSetupGenerated {

	public static void doSetup() {
		new RuleDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
