/*
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl;

import org.eclipse.xtext.resource.XtextResource;
import org.gyaltso.mdsca.ruledsl.resource.RulesResource;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RuleDslRuntimeModule extends AbstractRuleDslRuntimeModule {
	
	@Override
	public Class<? extends XtextResource> bindXtextResource() {
		return RulesResource.class;
	}
}
