/*
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRuleDslScopeProvider extends DelegatingScopeProvider {
}
