/**
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl.ruleDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Param Count Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodParamCountRule#getMax <em>Max</em>}</li>
 *   <li>{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodParamCountRule#isIgnoreOverriddenMethods <em>Ignore Overridden Methods</em>}</li>
 * </ul>
 *
 * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getMethodParamCountRule()
 * @model
 * @generated
 */
public interface MethodParamCountRule extends Rule
{
  /**
   * Returns the value of the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max</em>' attribute.
   * @see #setMax(int)
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getMethodParamCountRule_Max()
   * @model
   * @generated
   */
  int getMax();

  /**
   * Sets the value of the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodParamCountRule#getMax <em>Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max</em>' attribute.
   * @see #getMax()
   * @generated
   */
  void setMax(int value);

  /**
   * Returns the value of the '<em><b>Ignore Overridden Methods</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ignore Overridden Methods</em>' attribute.
   * @see #setIgnoreOverriddenMethods(boolean)
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getMethodParamCountRule_IgnoreOverriddenMethods()
   * @model
   * @generated
   */
  boolean isIgnoreOverriddenMethods();

  /**
   * Sets the value of the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodParamCountRule#isIgnoreOverriddenMethods <em>Ignore Overridden Methods</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ignore Overridden Methods</em>' attribute.
   * @see #isIgnoreOverriddenMethods()
   * @generated
   */
  void setIgnoreOverriddenMethods(boolean value);

} // MethodParamCountRule
