/**
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl.ruleDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Name Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#getFormat <em>Format</em>}</li>
 *   <li>{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isAllowClassName <em>Allow Class Name</em>}</li>
 *   <li>{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToPublic <em>Apply To Public</em>}</li>
 *   <li>{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToProtected <em>Apply To Protected</em>}</li>
 *   <li>{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToPackage <em>Apply To Package</em>}</li>
 *   <li>{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToPrivate <em>Apply To Private</em>}</li>
 * </ul>
 *
 * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getMethodNameRule()
 * @model
 * @generated
 */
public interface MethodNameRule extends Rule
{
  /**
   * Returns the value of the '<em><b>Format</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Format</em>' attribute.
   * @see #setFormat(String)
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getMethodNameRule_Format()
   * @model
   * @generated
   */
  String getFormat();

  /**
   * Sets the value of the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#getFormat <em>Format</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Format</em>' attribute.
   * @see #getFormat()
   * @generated
   */
  void setFormat(String value);

  /**
   * Returns the value of the '<em><b>Allow Class Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Allow Class Name</em>' attribute.
   * @see #setAllowClassName(boolean)
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getMethodNameRule_AllowClassName()
   * @model
   * @generated
   */
  boolean isAllowClassName();

  /**
   * Sets the value of the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isAllowClassName <em>Allow Class Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Allow Class Name</em>' attribute.
   * @see #isAllowClassName()
   * @generated
   */
  void setAllowClassName(boolean value);

  /**
   * Returns the value of the '<em><b>Apply To Public</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Apply To Public</em>' attribute.
   * @see #setApplyToPublic(boolean)
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getMethodNameRule_ApplyToPublic()
   * @model
   * @generated
   */
  boolean isApplyToPublic();

  /**
   * Sets the value of the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToPublic <em>Apply To Public</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Apply To Public</em>' attribute.
   * @see #isApplyToPublic()
   * @generated
   */
  void setApplyToPublic(boolean value);

  /**
   * Returns the value of the '<em><b>Apply To Protected</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Apply To Protected</em>' attribute.
   * @see #setApplyToProtected(boolean)
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getMethodNameRule_ApplyToProtected()
   * @model
   * @generated
   */
  boolean isApplyToProtected();

  /**
   * Sets the value of the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToProtected <em>Apply To Protected</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Apply To Protected</em>' attribute.
   * @see #isApplyToProtected()
   * @generated
   */
  void setApplyToProtected(boolean value);

  /**
   * Returns the value of the '<em><b>Apply To Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Apply To Package</em>' attribute.
   * @see #setApplyToPackage(boolean)
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getMethodNameRule_ApplyToPackage()
   * @model
   * @generated
   */
  boolean isApplyToPackage();

  /**
   * Sets the value of the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToPackage <em>Apply To Package</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Apply To Package</em>' attribute.
   * @see #isApplyToPackage()
   * @generated
   */
  void setApplyToPackage(boolean value);

  /**
   * Returns the value of the '<em><b>Apply To Private</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Apply To Private</em>' attribute.
   * @see #setApplyToPrivate(boolean)
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getMethodNameRule_ApplyToPrivate()
   * @model
   * @generated
   */
  boolean isApplyToPrivate();

  /**
   * Sets the value of the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToPrivate <em>Apply To Private</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Apply To Private</em>' attribute.
   * @see #isApplyToPrivate()
   * @generated
   */
  void setApplyToPrivate(boolean value);

} // MethodNameRule
