/**
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl.ruleDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Length Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodLengthRule#getMax <em>Max</em>}</li>
 *   <li>{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodLengthRule#isCountEmpty <em>Count Empty</em>}</li>
 * </ul>
 *
 * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getMethodLengthRule()
 * @model
 * @generated
 */
public interface MethodLengthRule extends Rule
{
  /**
   * Returns the value of the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max</em>' attribute.
   * @see #setMax(int)
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getMethodLengthRule_Max()
   * @model
   * @generated
   */
  int getMax();

  /**
   * Sets the value of the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodLengthRule#getMax <em>Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max</em>' attribute.
   * @see #getMax()
   * @generated
   */
  void setMax(int value);

  /**
   * Returns the value of the '<em><b>Count Empty</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Count Empty</em>' attribute.
   * @see #setCountEmpty(boolean)
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getMethodLengthRule_CountEmpty()
   * @model
   * @generated
   */
  boolean isCountEmpty();

  /**
   * Sets the value of the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodLengthRule#isCountEmpty <em>Count Empty</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Count Empty</em>' attribute.
   * @see #isCountEmpty()
   * @generated
   */
  void setCountEmpty(boolean value);

} // MethodLengthRule
