/**
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl.ruleDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage
 * @generated
 */
public interface RuleDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RuleDslFactory eINSTANCE = org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Rules File</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rules File</em>'.
   * @generated
   */
  RulesFile createRulesFile();

  /**
   * Returns a new object of class '<em>Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule</em>'.
   * @generated
   */
  Rule createRule();

  /**
   * Returns a new object of class '<em>Type Name Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type Name Rule</em>'.
   * @generated
   */
  TypeNameRule createTypeNameRule();

  /**
   * Returns a new object of class '<em>Method Name Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Method Name Rule</em>'.
   * @generated
   */
  MethodNameRule createMethodNameRule();

  /**
   * Returns a new object of class '<em>Method Length Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Method Length Rule</em>'.
   * @generated
   */
  MethodLengthRule createMethodLengthRule();

  /**
   * Returns a new object of class '<em>Method Param Count Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Method Param Count Rule</em>'.
   * @generated
   */
  MethodParamCountRule createMethodParamCountRule();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  RuleDslPackage getRuleDslPackage();

} //RuleDslFactory
