/**
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl.ruleDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rules File</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getMethodNameRule <em>Method Name Rule</em>}</li>
 *   <li>{@link org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getMethdLengthRule <em>Methd Length Rule</em>}</li>
 *   <li>{@link org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getMethodNoOfParamsRule <em>Method No Of Params Rule</em>}</li>
 *   <li>{@link org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getTypeName <em>Type Name</em>}</li>
 * </ul>
 *
 * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getRulesFile()
 * @model
 * @generated
 */
public interface RulesFile extends EObject
{
  /**
   * Returns the value of the '<em><b>Method Name Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method Name Rule</em>' containment reference.
   * @see #setMethodNameRule(Rule)
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getRulesFile_MethodNameRule()
   * @model containment="true"
   * @generated
   */
  Rule getMethodNameRule();

  /**
   * Sets the value of the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getMethodNameRule <em>Method Name Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Method Name Rule</em>' containment reference.
   * @see #getMethodNameRule()
   * @generated
   */
  void setMethodNameRule(Rule value);

  /**
   * Returns the value of the '<em><b>Methd Length Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Methd Length Rule</em>' containment reference.
   * @see #setMethdLengthRule(Rule)
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getRulesFile_MethdLengthRule()
   * @model containment="true"
   * @generated
   */
  Rule getMethdLengthRule();

  /**
   * Sets the value of the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getMethdLengthRule <em>Methd Length Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Methd Length Rule</em>' containment reference.
   * @see #getMethdLengthRule()
   * @generated
   */
  void setMethdLengthRule(Rule value);

  /**
   * Returns the value of the '<em><b>Method No Of Params Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method No Of Params Rule</em>' containment reference.
   * @see #setMethodNoOfParamsRule(Rule)
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getRulesFile_MethodNoOfParamsRule()
   * @model containment="true"
   * @generated
   */
  Rule getMethodNoOfParamsRule();

  /**
   * Sets the value of the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getMethodNoOfParamsRule <em>Method No Of Params Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Method No Of Params Rule</em>' containment reference.
   * @see #getMethodNoOfParamsRule()
   * @generated
   */
  void setMethodNoOfParamsRule(Rule value);

  /**
   * Returns the value of the '<em><b>Type Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Name</em>' containment reference.
   * @see #setTypeName(Rule)
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage#getRulesFile_TypeName()
   * @model containment="true"
   * @generated
   */
  Rule getTypeName();

  /**
   * Sets the value of the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getTypeName <em>Type Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Name</em>' containment reference.
   * @see #getTypeName()
   * @generated
   */
  void setTypeName(Rule value);

} // RulesFile
