/**
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl.ruleDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslFactory
 * @model kind="package"
 * @generated
 */
public interface RuleDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ruleDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.gyaltso.org/mdsca/ruledsl/RuleDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ruleDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RuleDslPackage eINSTANCE = org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RulesFileImpl <em>Rules File</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RulesFileImpl
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleDslPackageImpl#getRulesFile()
   * @generated
   */
  int RULES_FILE = 0;

  /**
   * The feature id for the '<em><b>Method Name Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES_FILE__METHOD_NAME_RULE = 0;

  /**
   * The feature id for the '<em><b>Methd Length Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES_FILE__METHD_LENGTH_RULE = 1;

  /**
   * The feature id for the '<em><b>Method No Of Params Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES_FILE__METHOD_NO_OF_PARAMS_RULE = 2;

  /**
   * The feature id for the '<em><b>Type Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES_FILE__TYPE_NAME = 3;

  /**
   * The number of structural features of the '<em>Rules File</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES_FILE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleImpl
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleDslPackageImpl#getRule()
   * @generated
   */
  int RULE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__NAME = 0;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.impl.TypeNameRuleImpl <em>Type Name Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.TypeNameRuleImpl
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleDslPackageImpl#getTypeNameRule()
   * @generated
   */
  int TYPE_NAME_RULE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_NAME_RULE__NAME = RULE__NAME;

  /**
   * The feature id for the '<em><b>Format</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_NAME_RULE__FORMAT = RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Apply To Public</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_NAME_RULE__APPLY_TO_PUBLIC = RULE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Apply To Protected</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_NAME_RULE__APPLY_TO_PROTECTED = RULE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Apply To Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_NAME_RULE__APPLY_TO_PACKAGE = RULE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Apply To Private</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_NAME_RULE__APPLY_TO_PRIVATE = RULE_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Type Name Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_NAME_RULE_FEATURE_COUNT = RULE_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.impl.MethodNameRuleImpl <em>Method Name Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.MethodNameRuleImpl
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleDslPackageImpl#getMethodNameRule()
   * @generated
   */
  int METHOD_NAME_RULE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_NAME_RULE__NAME = RULE__NAME;

  /**
   * The feature id for the '<em><b>Format</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_NAME_RULE__FORMAT = RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Allow Class Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_NAME_RULE__ALLOW_CLASS_NAME = RULE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Apply To Public</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_NAME_RULE__APPLY_TO_PUBLIC = RULE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Apply To Protected</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_NAME_RULE__APPLY_TO_PROTECTED = RULE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Apply To Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_NAME_RULE__APPLY_TO_PACKAGE = RULE_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Apply To Private</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_NAME_RULE__APPLY_TO_PRIVATE = RULE_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Method Name Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_NAME_RULE_FEATURE_COUNT = RULE_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.impl.MethodLengthRuleImpl <em>Method Length Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.MethodLengthRuleImpl
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleDslPackageImpl#getMethodLengthRule()
   * @generated
   */
  int METHOD_LENGTH_RULE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_LENGTH_RULE__NAME = RULE__NAME;

  /**
   * The feature id for the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_LENGTH_RULE__MAX = RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Count Empty</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_LENGTH_RULE__COUNT_EMPTY = RULE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Method Length Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_LENGTH_RULE_FEATURE_COUNT = RULE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.impl.MethodParamCountRuleImpl <em>Method Param Count Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.MethodParamCountRuleImpl
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleDslPackageImpl#getMethodParamCountRule()
   * @generated
   */
  int METHOD_PARAM_COUNT_RULE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_PARAM_COUNT_RULE__NAME = RULE__NAME;

  /**
   * The feature id for the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_PARAM_COUNT_RULE__MAX = RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ignore Overridden Methods</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_PARAM_COUNT_RULE__IGNORE_OVERRIDDEN_METHODS = RULE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Method Param Count Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_PARAM_COUNT_RULE_FEATURE_COUNT = RULE_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile <em>Rules File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rules File</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile
   * @generated
   */
  EClass getRulesFile();

  /**
   * Returns the meta object for the containment reference '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getMethodNameRule <em>Method Name Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Method Name Rule</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getMethodNameRule()
   * @see #getRulesFile()
   * @generated
   */
  EReference getRulesFile_MethodNameRule();

  /**
   * Returns the meta object for the containment reference '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getMethdLengthRule <em>Methd Length Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Methd Length Rule</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getMethdLengthRule()
   * @see #getRulesFile()
   * @generated
   */
  EReference getRulesFile_MethdLengthRule();

  /**
   * Returns the meta object for the containment reference '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getMethodNoOfParamsRule <em>Method No Of Params Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Method No Of Params Rule</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getMethodNoOfParamsRule()
   * @see #getRulesFile()
   * @generated
   */
  EReference getRulesFile_MethodNoOfParamsRule();

  /**
   * Returns the meta object for the containment reference '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getTypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type Name</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.RulesFile#getTypeName()
   * @see #getRulesFile()
   * @generated
   */
  EReference getRulesFile_TypeName();

  /**
   * Returns the meta object for class '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.Rule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.Rule#getName()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Name();

  /**
   * Returns the meta object for class '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.TypeNameRule <em>Type Name Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Name Rule</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.TypeNameRule
   * @generated
   */
  EClass getTypeNameRule();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.TypeNameRule#getFormat <em>Format</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Format</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.TypeNameRule#getFormat()
   * @see #getTypeNameRule()
   * @generated
   */
  EAttribute getTypeNameRule_Format();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.TypeNameRule#isApplyToPublic <em>Apply To Public</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Apply To Public</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.TypeNameRule#isApplyToPublic()
   * @see #getTypeNameRule()
   * @generated
   */
  EAttribute getTypeNameRule_ApplyToPublic();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.TypeNameRule#isApplyToProtected <em>Apply To Protected</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Apply To Protected</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.TypeNameRule#isApplyToProtected()
   * @see #getTypeNameRule()
   * @generated
   */
  EAttribute getTypeNameRule_ApplyToProtected();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.TypeNameRule#isApplyToPackage <em>Apply To Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Apply To Package</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.TypeNameRule#isApplyToPackage()
   * @see #getTypeNameRule()
   * @generated
   */
  EAttribute getTypeNameRule_ApplyToPackage();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.TypeNameRule#isApplyToPrivate <em>Apply To Private</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Apply To Private</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.TypeNameRule#isApplyToPrivate()
   * @see #getTypeNameRule()
   * @generated
   */
  EAttribute getTypeNameRule_ApplyToPrivate();

  /**
   * Returns the meta object for class '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule <em>Method Name Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method Name Rule</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule
   * @generated
   */
  EClass getMethodNameRule();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#getFormat <em>Format</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Format</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#getFormat()
   * @see #getMethodNameRule()
   * @generated
   */
  EAttribute getMethodNameRule_Format();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isAllowClassName <em>Allow Class Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Allow Class Name</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isAllowClassName()
   * @see #getMethodNameRule()
   * @generated
   */
  EAttribute getMethodNameRule_AllowClassName();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToPublic <em>Apply To Public</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Apply To Public</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToPublic()
   * @see #getMethodNameRule()
   * @generated
   */
  EAttribute getMethodNameRule_ApplyToPublic();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToProtected <em>Apply To Protected</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Apply To Protected</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToProtected()
   * @see #getMethodNameRule()
   * @generated
   */
  EAttribute getMethodNameRule_ApplyToProtected();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToPackage <em>Apply To Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Apply To Package</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToPackage()
   * @see #getMethodNameRule()
   * @generated
   */
  EAttribute getMethodNameRule_ApplyToPackage();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToPrivate <em>Apply To Private</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Apply To Private</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.MethodNameRule#isApplyToPrivate()
   * @see #getMethodNameRule()
   * @generated
   */
  EAttribute getMethodNameRule_ApplyToPrivate();

  /**
   * Returns the meta object for class '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodLengthRule <em>Method Length Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method Length Rule</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.MethodLengthRule
   * @generated
   */
  EClass getMethodLengthRule();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodLengthRule#getMax <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.MethodLengthRule#getMax()
   * @see #getMethodLengthRule()
   * @generated
   */
  EAttribute getMethodLengthRule_Max();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodLengthRule#isCountEmpty <em>Count Empty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Count Empty</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.MethodLengthRule#isCountEmpty()
   * @see #getMethodLengthRule()
   * @generated
   */
  EAttribute getMethodLengthRule_CountEmpty();

  /**
   * Returns the meta object for class '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodParamCountRule <em>Method Param Count Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method Param Count Rule</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.MethodParamCountRule
   * @generated
   */
  EClass getMethodParamCountRule();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodParamCountRule#getMax <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.MethodParamCountRule#getMax()
   * @see #getMethodParamCountRule()
   * @generated
   */
  EAttribute getMethodParamCountRule_Max();

  /**
   * Returns the meta object for the attribute '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.MethodParamCountRule#isIgnoreOverriddenMethods <em>Ignore Overridden Methods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ignore Overridden Methods</em>'.
   * @see org.gyaltso.mdsca.ruledsl.ruleDsl.MethodParamCountRule#isIgnoreOverriddenMethods()
   * @see #getMethodParamCountRule()
   * @generated
   */
  EAttribute getMethodParamCountRule_IgnoreOverriddenMethods();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RuleDslFactory getRuleDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RulesFileImpl <em>Rules File</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RulesFileImpl
     * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleDslPackageImpl#getRulesFile()
     * @generated
     */
    EClass RULES_FILE = eINSTANCE.getRulesFile();

    /**
     * The meta object literal for the '<em><b>Method Name Rule</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULES_FILE__METHOD_NAME_RULE = eINSTANCE.getRulesFile_MethodNameRule();

    /**
     * The meta object literal for the '<em><b>Methd Length Rule</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULES_FILE__METHD_LENGTH_RULE = eINSTANCE.getRulesFile_MethdLengthRule();

    /**
     * The meta object literal for the '<em><b>Method No Of Params Rule</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULES_FILE__METHOD_NO_OF_PARAMS_RULE = eINSTANCE.getRulesFile_MethodNoOfParamsRule();

    /**
     * The meta object literal for the '<em><b>Type Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULES_FILE__TYPE_NAME = eINSTANCE.getRulesFile_TypeName();

    /**
     * The meta object literal for the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleImpl
     * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleDslPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__NAME = eINSTANCE.getRule_Name();

    /**
     * The meta object literal for the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.impl.TypeNameRuleImpl <em>Type Name Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.TypeNameRuleImpl
     * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleDslPackageImpl#getTypeNameRule()
     * @generated
     */
    EClass TYPE_NAME_RULE = eINSTANCE.getTypeNameRule();

    /**
     * The meta object literal for the '<em><b>Format</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_NAME_RULE__FORMAT = eINSTANCE.getTypeNameRule_Format();

    /**
     * The meta object literal for the '<em><b>Apply To Public</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_NAME_RULE__APPLY_TO_PUBLIC = eINSTANCE.getTypeNameRule_ApplyToPublic();

    /**
     * The meta object literal for the '<em><b>Apply To Protected</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_NAME_RULE__APPLY_TO_PROTECTED = eINSTANCE.getTypeNameRule_ApplyToProtected();

    /**
     * The meta object literal for the '<em><b>Apply To Package</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_NAME_RULE__APPLY_TO_PACKAGE = eINSTANCE.getTypeNameRule_ApplyToPackage();

    /**
     * The meta object literal for the '<em><b>Apply To Private</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_NAME_RULE__APPLY_TO_PRIVATE = eINSTANCE.getTypeNameRule_ApplyToPrivate();

    /**
     * The meta object literal for the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.impl.MethodNameRuleImpl <em>Method Name Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.MethodNameRuleImpl
     * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleDslPackageImpl#getMethodNameRule()
     * @generated
     */
    EClass METHOD_NAME_RULE = eINSTANCE.getMethodNameRule();

    /**
     * The meta object literal for the '<em><b>Format</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_NAME_RULE__FORMAT = eINSTANCE.getMethodNameRule_Format();

    /**
     * The meta object literal for the '<em><b>Allow Class Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_NAME_RULE__ALLOW_CLASS_NAME = eINSTANCE.getMethodNameRule_AllowClassName();

    /**
     * The meta object literal for the '<em><b>Apply To Public</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_NAME_RULE__APPLY_TO_PUBLIC = eINSTANCE.getMethodNameRule_ApplyToPublic();

    /**
     * The meta object literal for the '<em><b>Apply To Protected</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_NAME_RULE__APPLY_TO_PROTECTED = eINSTANCE.getMethodNameRule_ApplyToProtected();

    /**
     * The meta object literal for the '<em><b>Apply To Package</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_NAME_RULE__APPLY_TO_PACKAGE = eINSTANCE.getMethodNameRule_ApplyToPackage();

    /**
     * The meta object literal for the '<em><b>Apply To Private</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_NAME_RULE__APPLY_TO_PRIVATE = eINSTANCE.getMethodNameRule_ApplyToPrivate();

    /**
     * The meta object literal for the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.impl.MethodLengthRuleImpl <em>Method Length Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.MethodLengthRuleImpl
     * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleDslPackageImpl#getMethodLengthRule()
     * @generated
     */
    EClass METHOD_LENGTH_RULE = eINSTANCE.getMethodLengthRule();

    /**
     * The meta object literal for the '<em><b>Max</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_LENGTH_RULE__MAX = eINSTANCE.getMethodLengthRule_Max();

    /**
     * The meta object literal for the '<em><b>Count Empty</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_LENGTH_RULE__COUNT_EMPTY = eINSTANCE.getMethodLengthRule_CountEmpty();

    /**
     * The meta object literal for the '{@link org.gyaltso.mdsca.ruledsl.ruleDsl.impl.MethodParamCountRuleImpl <em>Method Param Count Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.MethodParamCountRuleImpl
     * @see org.gyaltso.mdsca.ruledsl.ruleDsl.impl.RuleDslPackageImpl#getMethodParamCountRule()
     * @generated
     */
    EClass METHOD_PARAM_COUNT_RULE = eINSTANCE.getMethodParamCountRule();

    /**
     * The meta object literal for the '<em><b>Max</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_PARAM_COUNT_RULE__MAX = eINSTANCE.getMethodParamCountRule_Max();

    /**
     * The meta object literal for the '<em><b>Ignore Overridden Methods</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_PARAM_COUNT_RULE__IGNORE_OVERRIDDEN_METHODS = eINSTANCE.getMethodParamCountRule_IgnoreOverriddenMethods();

  }

} //RuleDslPackage
