/*
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RuleDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class RulesFileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.gyaltso.mdsca.ruledsl.RuleDsl.RulesFile");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMethodNameRuleAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMethodNameRuleMethodNameRuleParserRuleCall_0_0 = (RuleCall)cMethodNameRuleAssignment_0.eContents().get(0);
		private final Assignment cMethdLengthRuleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMethdLengthRuleMethodLengthRuleParserRuleCall_1_0 = (RuleCall)cMethdLengthRuleAssignment_1.eContents().get(0);
		private final Assignment cMethodNoOfParamsRuleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMethodNoOfParamsRuleMethodParamCountRuleParserRuleCall_2_0 = (RuleCall)cMethodNoOfParamsRuleAssignment_2.eContents().get(0);
		private final Assignment cTypeNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeNameTypeNameRuleParserRuleCall_3_0 = (RuleCall)cTypeNameAssignment_3.eContents().get(0);
		
		//RulesFile:
		//	methodNameRule=MethodNameRule?
		//	methdLengthRule=MethodLengthRule?
		//	methodNoOfParamsRule=MethodParamCountRule?
		//	typeName=TypeNameRule?;
		@Override public ParserRule getRule() { return rule; }
		
		//methodNameRule=MethodNameRule? methdLengthRule=MethodLengthRule? methodNoOfParamsRule=MethodParamCountRule?
		//typeName=TypeNameRule?
		public Group getGroup() { return cGroup; }
		
		//methodNameRule=MethodNameRule?
		public Assignment getMethodNameRuleAssignment_0() { return cMethodNameRuleAssignment_0; }
		
		//MethodNameRule
		public RuleCall getMethodNameRuleMethodNameRuleParserRuleCall_0_0() { return cMethodNameRuleMethodNameRuleParserRuleCall_0_0; }
		
		//methdLengthRule=MethodLengthRule?
		public Assignment getMethdLengthRuleAssignment_1() { return cMethdLengthRuleAssignment_1; }
		
		//MethodLengthRule
		public RuleCall getMethdLengthRuleMethodLengthRuleParserRuleCall_1_0() { return cMethdLengthRuleMethodLengthRuleParserRuleCall_1_0; }
		
		//methodNoOfParamsRule=MethodParamCountRule?
		public Assignment getMethodNoOfParamsRuleAssignment_2() { return cMethodNoOfParamsRuleAssignment_2; }
		
		//MethodParamCountRule
		public RuleCall getMethodNoOfParamsRuleMethodParamCountRuleParserRuleCall_2_0() { return cMethodNoOfParamsRuleMethodParamCountRuleParserRuleCall_2_0; }
		
		//typeName=TypeNameRule?
		public Assignment getTypeNameAssignment_3() { return cTypeNameAssignment_3; }
		
		//TypeNameRule
		public RuleCall getTypeNameTypeNameRuleParserRuleCall_3_0() { return cTypeNameTypeNameRuleParserRuleCall_3_0; }
	}
	public class TypeNameRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.gyaltso.mdsca.ruledsl.RuleDsl.TypeNameRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTypeNameRuleAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cNameTypeNameKeyword_1_0 = (Keyword)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFormatKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFormatAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFormatSTRINGTerminalRuleCall_4_0 = (RuleCall)cFormatAssignment_4.eContents().get(0);
		private final Keyword cApplyToPublicKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cApplyToPublicAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cApplyToPublicBOOLEANTerminalRuleCall_6_0 = (RuleCall)cApplyToPublicAssignment_6.eContents().get(0);
		private final Keyword cApplyToProtectedKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cApplyToProtectedAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cApplyToProtectedBOOLEANTerminalRuleCall_8_0 = (RuleCall)cApplyToProtectedAssignment_8.eContents().get(0);
		private final Keyword cApplyToPackageKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cApplyToPackageAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cApplyToPackageBOOLEANTerminalRuleCall_10_0 = (RuleCall)cApplyToPackageAssignment_10.eContents().get(0);
		private final Keyword cApplyToPrivateKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cApplyToPrivateAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cApplyToPrivateBOOLEANTerminalRuleCall_12_0 = (RuleCall)cApplyToPrivateAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//TypeNameRule Rule:
		//	{TypeNameRule} name='TypeName' '{'
		//	'format' format=STRING
		//	'applyToPublic' applyToPublic=BOOLEAN
		//	'applyToProtected' applyToProtected=BOOLEAN
		//	'applyToPackage' applyToPackage=BOOLEAN
		//	'applyToPrivate' applyToPrivate=BOOLEAN
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{TypeNameRule} name='TypeName' '{' 'format' format=STRING 'applyToPublic' applyToPublic=BOOLEAN 'applyToProtected'
		//applyToProtected=BOOLEAN 'applyToPackage' applyToPackage=BOOLEAN 'applyToPrivate' applyToPrivate=BOOLEAN '}'
		public Group getGroup() { return cGroup; }
		
		//{TypeNameRule}
		public Action getTypeNameRuleAction_0() { return cTypeNameRuleAction_0; }
		
		//name='TypeName'
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//'TypeName'
		public Keyword getNameTypeNameKeyword_1_0() { return cNameTypeNameKeyword_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'format'
		public Keyword getFormatKeyword_3() { return cFormatKeyword_3; }
		
		//format=STRING
		public Assignment getFormatAssignment_4() { return cFormatAssignment_4; }
		
		//STRING
		public RuleCall getFormatSTRINGTerminalRuleCall_4_0() { return cFormatSTRINGTerminalRuleCall_4_0; }
		
		//'applyToPublic'
		public Keyword getApplyToPublicKeyword_5() { return cApplyToPublicKeyword_5; }
		
		//applyToPublic=BOOLEAN
		public Assignment getApplyToPublicAssignment_6() { return cApplyToPublicAssignment_6; }
		
		//BOOLEAN
		public RuleCall getApplyToPublicBOOLEANTerminalRuleCall_6_0() { return cApplyToPublicBOOLEANTerminalRuleCall_6_0; }
		
		//'applyToProtected'
		public Keyword getApplyToProtectedKeyword_7() { return cApplyToProtectedKeyword_7; }
		
		//applyToProtected=BOOLEAN
		public Assignment getApplyToProtectedAssignment_8() { return cApplyToProtectedAssignment_8; }
		
		//BOOLEAN
		public RuleCall getApplyToProtectedBOOLEANTerminalRuleCall_8_0() { return cApplyToProtectedBOOLEANTerminalRuleCall_8_0; }
		
		//'applyToPackage'
		public Keyword getApplyToPackageKeyword_9() { return cApplyToPackageKeyword_9; }
		
		//applyToPackage=BOOLEAN
		public Assignment getApplyToPackageAssignment_10() { return cApplyToPackageAssignment_10; }
		
		//BOOLEAN
		public RuleCall getApplyToPackageBOOLEANTerminalRuleCall_10_0() { return cApplyToPackageBOOLEANTerminalRuleCall_10_0; }
		
		//'applyToPrivate'
		public Keyword getApplyToPrivateKeyword_11() { return cApplyToPrivateKeyword_11; }
		
		//applyToPrivate=BOOLEAN
		public Assignment getApplyToPrivateAssignment_12() { return cApplyToPrivateAssignment_12; }
		
		//BOOLEAN
		public RuleCall getApplyToPrivateBOOLEANTerminalRuleCall_12_0() { return cApplyToPrivateBOOLEANTerminalRuleCall_12_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class MethodNameRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.gyaltso.mdsca.ruledsl.RuleDsl.MethodNameRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMethodNameRuleAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cNameMethodNameRuleKeyword_1_0 = (Keyword)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFormatKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFormatAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFormatSTRINGTerminalRuleCall_4_0 = (RuleCall)cFormatAssignment_4.eContents().get(0);
		private final Keyword cAllowClassNameKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cAllowClassNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cAllowClassNameBOOLEANTerminalRuleCall_6_0 = (RuleCall)cAllowClassNameAssignment_6.eContents().get(0);
		private final Keyword cApplyToPublicKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cApplyToPublicAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cApplyToPublicBOOLEANTerminalRuleCall_8_0 = (RuleCall)cApplyToPublicAssignment_8.eContents().get(0);
		private final Keyword cApplyToProtectedKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cApplyToProtectedAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cApplyToProtectedBOOLEANTerminalRuleCall_10_0 = (RuleCall)cApplyToProtectedAssignment_10.eContents().get(0);
		private final Keyword cApplyToPackageKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cApplyToPackageAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cApplyToPackageBOOLEANTerminalRuleCall_12_0 = (RuleCall)cApplyToPackageAssignment_12.eContents().get(0);
		private final Keyword cApplyToPrivateKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cApplyToPrivateAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cApplyToPrivateBOOLEANTerminalRuleCall_14_0 = (RuleCall)cApplyToPrivateAssignment_14.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//MethodNameRule Rule:
		//	{MethodNameRule} name='MethodNameRule' '{'
		//	'format' format=STRING
		//	'allowClassName' allowClassName=BOOLEAN
		//	'applyToPublic' applyToPublic=BOOLEAN
		//	'applyToProtected' applyToProtected=BOOLEAN
		//	'applyToPackage' applyToPackage=BOOLEAN
		//	'applyToPrivate' applyToPrivate=BOOLEAN
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{MethodNameRule} name='MethodNameRule' '{' 'format' format=STRING 'allowClassName' allowClassName=BOOLEAN
		//'applyToPublic' applyToPublic=BOOLEAN 'applyToProtected' applyToProtected=BOOLEAN 'applyToPackage'
		//applyToPackage=BOOLEAN 'applyToPrivate' applyToPrivate=BOOLEAN '}'
		public Group getGroup() { return cGroup; }
		
		//{MethodNameRule}
		public Action getMethodNameRuleAction_0() { return cMethodNameRuleAction_0; }
		
		//name='MethodNameRule'
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//'MethodNameRule'
		public Keyword getNameMethodNameRuleKeyword_1_0() { return cNameMethodNameRuleKeyword_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'format'
		public Keyword getFormatKeyword_3() { return cFormatKeyword_3; }
		
		//format=STRING
		public Assignment getFormatAssignment_4() { return cFormatAssignment_4; }
		
		//STRING
		public RuleCall getFormatSTRINGTerminalRuleCall_4_0() { return cFormatSTRINGTerminalRuleCall_4_0; }
		
		//'allowClassName'
		public Keyword getAllowClassNameKeyword_5() { return cAllowClassNameKeyword_5; }
		
		//allowClassName=BOOLEAN
		public Assignment getAllowClassNameAssignment_6() { return cAllowClassNameAssignment_6; }
		
		//BOOLEAN
		public RuleCall getAllowClassNameBOOLEANTerminalRuleCall_6_0() { return cAllowClassNameBOOLEANTerminalRuleCall_6_0; }
		
		//'applyToPublic'
		public Keyword getApplyToPublicKeyword_7() { return cApplyToPublicKeyword_7; }
		
		//applyToPublic=BOOLEAN
		public Assignment getApplyToPublicAssignment_8() { return cApplyToPublicAssignment_8; }
		
		//BOOLEAN
		public RuleCall getApplyToPublicBOOLEANTerminalRuleCall_8_0() { return cApplyToPublicBOOLEANTerminalRuleCall_8_0; }
		
		//'applyToProtected'
		public Keyword getApplyToProtectedKeyword_9() { return cApplyToProtectedKeyword_9; }
		
		//applyToProtected=BOOLEAN
		public Assignment getApplyToProtectedAssignment_10() { return cApplyToProtectedAssignment_10; }
		
		//BOOLEAN
		public RuleCall getApplyToProtectedBOOLEANTerminalRuleCall_10_0() { return cApplyToProtectedBOOLEANTerminalRuleCall_10_0; }
		
		//'applyToPackage'
		public Keyword getApplyToPackageKeyword_11() { return cApplyToPackageKeyword_11; }
		
		//applyToPackage=BOOLEAN
		public Assignment getApplyToPackageAssignment_12() { return cApplyToPackageAssignment_12; }
		
		//BOOLEAN
		public RuleCall getApplyToPackageBOOLEANTerminalRuleCall_12_0() { return cApplyToPackageBOOLEANTerminalRuleCall_12_0; }
		
		//'applyToPrivate'
		public Keyword getApplyToPrivateKeyword_13() { return cApplyToPrivateKeyword_13; }
		
		//applyToPrivate=BOOLEAN
		public Assignment getApplyToPrivateAssignment_14() { return cApplyToPrivateAssignment_14; }
		
		//BOOLEAN
		public RuleCall getApplyToPrivateBOOLEANTerminalRuleCall_14_0() { return cApplyToPrivateBOOLEANTerminalRuleCall_14_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	public class MethodLengthRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.gyaltso.mdsca.ruledsl.RuleDsl.MethodLengthRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMethodLengthRuleAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cNameMethodLengthRuleKeyword_1_0 = (Keyword)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMaxKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMaxAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMaxINTTerminalRuleCall_4_0 = (RuleCall)cMaxAssignment_4.eContents().get(0);
		private final Keyword cCountEmptyKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cCountEmptyAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCountEmptyBOOLEANTerminalRuleCall_6_0 = (RuleCall)cCountEmptyAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//MethodLengthRule Rule:
		//	{MethodLengthRule} name='MethodLengthRule' '{'
		//	'max' max=INT
		//	'countEmpty' countEmpty=BOOLEAN
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{MethodLengthRule} name='MethodLengthRule' '{' 'max' max=INT 'countEmpty' countEmpty=BOOLEAN '}'
		public Group getGroup() { return cGroup; }
		
		//{MethodLengthRule}
		public Action getMethodLengthRuleAction_0() { return cMethodLengthRuleAction_0; }
		
		//name='MethodLengthRule'
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//'MethodLengthRule'
		public Keyword getNameMethodLengthRuleKeyword_1_0() { return cNameMethodLengthRuleKeyword_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'max'
		public Keyword getMaxKeyword_3() { return cMaxKeyword_3; }
		
		//max=INT
		public Assignment getMaxAssignment_4() { return cMaxAssignment_4; }
		
		//INT
		public RuleCall getMaxINTTerminalRuleCall_4_0() { return cMaxINTTerminalRuleCall_4_0; }
		
		//'countEmpty'
		public Keyword getCountEmptyKeyword_5() { return cCountEmptyKeyword_5; }
		
		//countEmpty=BOOLEAN
		public Assignment getCountEmptyAssignment_6() { return cCountEmptyAssignment_6; }
		
		//BOOLEAN
		public RuleCall getCountEmptyBOOLEANTerminalRuleCall_6_0() { return cCountEmptyBOOLEANTerminalRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class MethodParamCountRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.gyaltso.mdsca.ruledsl.RuleDsl.MethodParamCountRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMethodParamCountRuleAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cNameMethodParamLengthRuleKeyword_1_0 = (Keyword)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMaxKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMaxAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMaxINTTerminalRuleCall_4_0 = (RuleCall)cMaxAssignment_4.eContents().get(0);
		private final Keyword cIgnoreOverriddenMethodsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cIgnoreOverriddenMethodsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cIgnoreOverriddenMethodsBOOLEANTerminalRuleCall_6_0 = (RuleCall)cIgnoreOverriddenMethodsAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//MethodParamCountRule Rule:
		//	{MethodParamCountRule} name='MethodParamLengthRule' '{'
		//	'max' max=INT
		//	'ignoreOverriddenMethods' ignoreOverriddenMethods=BOOLEAN
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{MethodParamCountRule} name='MethodParamLengthRule' '{' 'max' max=INT 'ignoreOverriddenMethods'
		//ignoreOverriddenMethods=BOOLEAN '}'
		public Group getGroup() { return cGroup; }
		
		//{MethodParamCountRule}
		public Action getMethodParamCountRuleAction_0() { return cMethodParamCountRuleAction_0; }
		
		//name='MethodParamLengthRule'
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//'MethodParamLengthRule'
		public Keyword getNameMethodParamLengthRuleKeyword_1_0() { return cNameMethodParamLengthRuleKeyword_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'max'
		public Keyword getMaxKeyword_3() { return cMaxKeyword_3; }
		
		//max=INT
		public Assignment getMaxAssignment_4() { return cMaxAssignment_4; }
		
		//INT
		public RuleCall getMaxINTTerminalRuleCall_4_0() { return cMaxINTTerminalRuleCall_4_0; }
		
		//'ignoreOverriddenMethods'
		public Keyword getIgnoreOverriddenMethodsKeyword_5() { return cIgnoreOverriddenMethodsKeyword_5; }
		
		//ignoreOverriddenMethods=BOOLEAN
		public Assignment getIgnoreOverriddenMethodsAssignment_6() { return cIgnoreOverriddenMethodsAssignment_6; }
		
		//BOOLEAN
		public RuleCall getIgnoreOverriddenMethodsBOOLEANTerminalRuleCall_6_0() { return cIgnoreOverriddenMethodsBOOLEANTerminalRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	
	private final RulesFileElements pRulesFile;
	private final TypeNameRuleElements pTypeNameRule;
	private final MethodNameRuleElements pMethodNameRule;
	private final MethodLengthRuleElements pMethodLengthRule;
	private final MethodParamCountRuleElements pMethodParamCountRule;
	private final TerminalRule tBOOLEAN;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RuleDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRulesFile = new RulesFileElements();
		this.pTypeNameRule = new TypeNameRuleElements();
		this.pMethodNameRule = new MethodNameRuleElements();
		this.pMethodLengthRule = new MethodLengthRuleElements();
		this.pMethodParamCountRule = new MethodParamCountRuleElements();
		this.tBOOLEAN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.gyaltso.mdsca.ruledsl.RuleDsl.BOOLEAN");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.gyaltso.mdsca.ruledsl.RuleDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RulesFile:
	//	methodNameRule=MethodNameRule?
	//	methdLengthRule=MethodLengthRule?
	//	methodNoOfParamsRule=MethodParamCountRule?
	//	typeName=TypeNameRule?;
	public RulesFileElements getRulesFileAccess() {
		return pRulesFile;
	}
	
	public ParserRule getRulesFileRule() {
		return getRulesFileAccess().getRule();
	}
	
	//TypeNameRule Rule:
	//	{TypeNameRule} name='TypeName' '{'
	//	'format' format=STRING
	//	'applyToPublic' applyToPublic=BOOLEAN
	//	'applyToProtected' applyToProtected=BOOLEAN
	//	'applyToPackage' applyToPackage=BOOLEAN
	//	'applyToPrivate' applyToPrivate=BOOLEAN
	//	'}';
	public TypeNameRuleElements getTypeNameRuleAccess() {
		return pTypeNameRule;
	}
	
	public ParserRule getTypeNameRuleRule() {
		return getTypeNameRuleAccess().getRule();
	}
	
	//MethodNameRule Rule:
	//	{MethodNameRule} name='MethodNameRule' '{'
	//	'format' format=STRING
	//	'allowClassName' allowClassName=BOOLEAN
	//	'applyToPublic' applyToPublic=BOOLEAN
	//	'applyToProtected' applyToProtected=BOOLEAN
	//	'applyToPackage' applyToPackage=BOOLEAN
	//	'applyToPrivate' applyToPrivate=BOOLEAN
	//	'}';
	public MethodNameRuleElements getMethodNameRuleAccess() {
		return pMethodNameRule;
	}
	
	public ParserRule getMethodNameRuleRule() {
		return getMethodNameRuleAccess().getRule();
	}
	
	//MethodLengthRule Rule:
	//	{MethodLengthRule} name='MethodLengthRule' '{'
	//	'max' max=INT
	//	'countEmpty' countEmpty=BOOLEAN
	//	'}';
	public MethodLengthRuleElements getMethodLengthRuleAccess() {
		return pMethodLengthRule;
	}
	
	public ParserRule getMethodLengthRuleRule() {
		return getMethodLengthRuleAccess().getRule();
	}
	
	//MethodParamCountRule Rule:
	//	{MethodParamCountRule} name='MethodParamLengthRule' '{'
	//	'max' max=INT
	//	'ignoreOverriddenMethods' ignoreOverriddenMethods=BOOLEAN
	//	'}';
	public MethodParamCountRuleElements getMethodParamCountRuleAccess() {
		return pMethodParamCountRule;
	}
	
	public ParserRule getMethodParamCountRuleRule() {
		return getMethodParamCountRuleAccess().getRule();
	}
	
	//terminal BOOLEAN returns ecore::EBoolean:
	//	'true' | 'false';
	public TerminalRule getBOOLEANRule() {
		return tBOOLEAN;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
