/*
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl.ide;


/**
 * Use this class to register ide components.
 */
public class RuleDslIdeModule extends AbstractRuleDslIdeModule {
}
