/*
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractRuleDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.gyaltso.mdsca.ruledsl.ruleDsl.RuleDslPackage.eINSTANCE);
		return result;
	}
}
