/*
 * generated by Xtext 2.23.0
 */
package org.gyaltso.mdsca.ruledsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RuleDslUiModule extends AbstractRuleDslUiModule {

	public RuleDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
